icon-ch1-eps:
  rotlatlon:
    dx: 0.01
    dy: 0.01
    xmin: -6.86
    xmax: 4.83
    ymin: -4.46
    ymax: 3.39
    north_pole_lon: 190.0
    north_pole_lat: 43.0
  geolatlon:
    dx: 0.01
    dy: 0.01
    xmin: 10.0
    xmax: 13.0
    ymin: 45.6
    ymax: 47.8

icon-ch2-eps:
  rotlatlon:
    dx: 0.02
    dy: 0.02
    xmin: -6.82
    xmax: 4.8
    ymin: -4.42
    ymax: 3.36
    north_pole_lon: 190.0
    north_pole_lat: 43.0
  geolatlon:
    dx: 0.02
    dy: 0.02
    xmin: 5.5
    xmax: 16.9
    ymin: 43.6
    ymax: 50.0
