pipeline {
    environment {
       PATH = "$WORKSPACE/miniconda/bin:$PATH"
    }
    agent {
        label 'tsa'
    }

    stages {
        stage('setup miniconda') {
            steps {
                sh 'curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh'
                sh 'bash miniconda.sh -b -p $WORKSPACE/miniconda'
                sh 'conda config --set always_yes yes --set changeps1 no'
                sh 'conda config --add channels conda-forge'
                sh 'conda create -n idpi --file requirements.txt'
                sh 'rm miniconda.sh'
            }        
        }
    }
}