# Standard library
import dataclasses as dc

# Third-party
import pytest
from numpy.testing import assert_allclose

# First-party
from idpi import grib_decoder
from idpi.operators import regrid
from idpi.operators.hzerocl import fhzerocl


def test_regrid(data_dir, fieldextra):
    datafile = data_dir / "lfff00000000.ch"
    cdatafile = data_dir / "lfff00000000c.ch"

    reader = grib_decoder.GribReader.from_files([cdatafile, datafile])
    ds = reader.load_fieldnames(["T", "HHL"])

    hzerocl = fhzerocl(ds["T"], ds["HHL"], extrapolate=True)
    out_regrid_target = "swiss,549500,149500,650500,250500,1000,1000"
    dst = regrid.RegularGrid.parse_regrid_operator(out_regrid_target)
    hzerocl.attrs["geography"] = ds["HHL"].geography
    observed = regrid.regrid(hzerocl, dst, regrid.Resampling.bilinear)

    fx_ds = fieldextra("regrid", out_regrid_target=out_regrid_target)
    expected = fx_ds["HZEROCL"]

    # The regrid operator is evaluated indirectly by comparing the output
    # to the one that is generated by fieldextra. Therefore, the reprojection errors
    # will manifest factored by the horizontal gradient of the supporting field.
    assert_allclose(observed, expected, rtol=5e-4)


def assert_close_enough(src, dst, rel):
    for field in dc.fields(src):
        if field.type == float:
            assert getattr(src, field.name) == pytest.approx(
                getattr(dst, field.name), rel=rel
            )
        else:
            assert getattr(src, field.name) == getattr(dst, field.name)


def test_to_crs():
    # 100km x 100km around Bern, LV03 -> LV 95
    nx, ny = 1001, 1000
    xmin, xmax = 550_000, 650_000
    ymin, ymax = 150_000, 250_000
    xoff = 2_000_000
    yoff = 1_000_000
    src = regrid.RegularGrid("epsg:21781", nx, ny, xmin, xmax, ymin, ymax)
    expected = regrid.RegularGrid(
        "epsg:2056", nx, ny, xmin + xoff, xmax + xoff, ymin + yoff, ymax + yoff
    )

    observed = src.to_crs("epsg:2056", dst_width=src.nx, dst_height=src.ny)

    # There's a bit less than half a pixel error...
    assert_close_enough(observed, expected, rel=1e-3)
